---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.11.1
    helm:
      releaseName: loki
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 4.2.1
    helm:
      releaseName: promtail
      values: |
        config:
          lokiAddress: http://loki:3100/loki/api/v1/push
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts/
    targetRevision: 15.9.0
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          enabled: false
        pushgateway:
          enabled: false
        serviceAccounts:
          alertmanager:
            create: false
          pushgateway:
            create: false
        persistentVolume:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts/
    targetRevision: 6.29.4
    helm:
      releaseName: grafana
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - grafana.traineeship-2022.axxes.cloud
        adminPassword: notAdmin
        plugins:
          - grafana-piechart-panel
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server
                access: proxy
              - name: Loki
                type: loki
                url: http://loki:3100/
                access: proxy
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            kube-state-metrics-v2:
              gnetId: 13332
              revision: 12
              datasource: Prometheus
            node-exporter-full:
              gnetId: 1860
              revision: 27
              datasource: Prometheus
            traefik:
              gnetId: 11462
              revision: 1
              datasource: Prometheus
            kubernetes-views-global:
              gnetId: 15757
              revision: 16
              datasource: Prometheus
            kubernetes-views-pods:
              gnetId: 15760
              revision: 11
              datasource: Prometheus
            kubernetes-views-nodes:
              gnetId: 15759
              revision: 9
              datasource: Prometheus
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true