apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 10.24.3
    helm:
      releaseName: traefik
      values: |
        ingressClass:
          enabled: true
        providers:
          kubernetesIngress:
            namespaces:
              - argocd
            publishedService:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true